steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_APP_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_APP_NAME}:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    id: 'build-image'

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_APP_NAME}'
    id: 'push-image'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_APP_NAME}:${SHORT_SHA}'
      - '--platform'
      - 'managed'
      - '--region'
      - '${_REGION}'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'VITE_API_URL=/api,VITE_API_VERSION=v1,VITE_ADMIN_EMAIL=${_ADMIN_EMAIL},VITE_GOOGLE_PROJECT_ID=${PROJECT_ID},VITE_GOOGLE_CLIENT_ID=${_CLIENT_ID},VITE_GOOGLE_REDIRECT_URI=/auth/google/callback,GOOGLE_CLOUD_PROJECT_ID=${PROJECT_ID},GOOGLE_CLOUD_PROJECT=${PROJECT_ID},GCP_PROJECT=${PROJECT_ID},GCP_LOCATION=${_GCP_LOCATION},GCP_REGION=${_GCP_REGION},VITE_GOOGLE_CLIENT_SECRET=${_CLIENT_SECRET},SUPER_ADMIN_EMAIL=${_ADMIN_EMAIL}'
    id: 'deploy-cloud-run'

# Substitution variables (set these in Cloud Build triggers)
# _REGION: us-central1 (or your preferred region)
# _REPO_NAME: dataplex-business-ui-artifact (or your artifact repository name)
# _APP_NAME: dataplex-business-ui (or your app name)
# _SERVICE_NAME: dataplex-business-ui (or your Cloud Run service name)
# _ADMIN_EMAIL: your-admin@example.com
# _CLIENT_ID: your-oauth-client-id
# _CLIENT_SECRET: your-oauth-client-secret
# _GCP_LOCATION: global (or your Dataplex location)
# _GCP_REGION: global (or your Dataplex region)

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_APP_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_APP_NAME}:latest'



